create database dbSoda2
go

USE dbSoda2
GO

/****** base datos proyecto soda ******/
SET ANSI_NULLS ON   /*no tiene  funciones utiles pero*/
GO                 /*es mejor dejarlo por el store procedures*/
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Usuarios](
	[ID_USUARIOS] [int] IDENTITY(1,1) NOT NULL,
	[ID_PRODUCTOS] [int]  NOT NULL,
	[ROL_USUARIO] [nvarchar](100) NULL,
	[NOMBRE] [nvarchar](100) NULL,
	[APELLIDO][nvarchar](100) NULL,
	[NUMERO][nvarchar](100) NULL,
	[DESCRIPCION] [nvarchar](max) NOT NULL,
	[REQUEST] [nvarchar](max) NOT NULL,
	[RESPONSE] [nvarchar](max) NOT NULL,
	[FECHA_REGISTRO] [datetime] NOT NULL,
 CONSTRAINT [PK_Usuarios] PRIMARY KEY CLUSTERED ([ID_USUARIOS] ASC)
	WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]) 
	ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRODUCTOS_SODA](
	[ID_PRODUCTOS] [int] IDENTITY(1,1) NOT NULL,
	[ID_PEDIDOS] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [nvarchar](max) NULL,
	[DESCRIPCION] [nvarchar](max) NULL,
	[PRECIO] [int] NULL,
	[DISPONIBLE] [nvarchar](max) NULL,
	[FECHA_REGISTRO] [datetime] NULL,
 CONSTRAINT [PK_PRODUCTOS_SODA] PRIMARY KEY CLUSTERED  
(
	[ID_PRODUCTOS] ASC),
	 CONSTRAINT FK_ID_USUARIO_PRODUCTOS FOREIGN KEY (ID_USUARIOS) REFERENCES USUARIO(ID_USUARIOS) 
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PEDIDOS_SODA](
	[ID_PEDIDOS] [int] IDENTITY(1,1) NOT NULL,
	[ID_USUARIOS] [int] NULL,
	[FECHA_REGISTRO] [datetime] NULL,
	[ESTADO] [nvarchar](max) NULL,
	[ADICIONAL] [nvarchar](max) NULL,
	[PRECIOTOTAL] [int] NULL,
 CONSTRAINT [PK_PEDIDOS_SODA] PRIMARY KEY CLUSTERED 
(
	[ID_PEDIDOS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
CREATE TABLE [dbo].[ERROR_DB_SODA](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[SEVERIDAD] [int] NULL,
	[STORE_PROCEDURE] [nvarchar](50) NULL,
	[NUMERO] [int] NULL,
	[DESCRIPCION] [nvarchar](max) NULL,
	[LINEA] [int] NULL,
	[FECHA_HORA] [datetime] NULL,
 CONSTRAINT [PK_ERROR_DB_SODA] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RESPUESTA](
	[ID_USUARIOS] [int] IDENTITY(1,1) NOT NULL,
	[MENSAJE] [nvarchar](max) NULL,
	[FECHA_REGISTRO] [datetime] NULL,
 CONSTRAINT [PK_RESPUESTA] PRIMARY KEY CLUSTERED 
(
	[ID_USUARIOS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PUBLICAR_RESPUESTA](
	[ID_PUBLICACION_RESPUESTA] [int] IDENTITY(1,1) NOT NULL,
	[ID_PUBLICACION] [int] NOT NULL,
	[ID_RESPUESTA] [int] NOT NULL,
	[FECHA_REGISTRO] [datetime] NOT NULL,
 CONSTRAINT [PK_PUBLICAR_RESPUESTA] PRIMARY KEY CLUSTERED 
(
	[ID_PUBLICACION_RESPUESTA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO



CREATE PROCEDURE [dbo].[SP_INSERTAR_USUARIO]
(
    @ID_PRODUCTOS INT,
    @ROL_USUARIO NVARCHAR(100),
    @NOMBRE NVARCHAR(100),
    @APELLIDO NVARCHAR(100),
    @NUMERO NVARCHAR(100),
    @DESCRIPCION NVARCHAR(MAX),
    @REQUEST NVARCHAR(MAX),
    @RESPONSE NVARCHAR(MAX),
    @FECHA_REGISTRO DATETIME,
    @ID_RETURN INT OUTPUT,
    @ERROR_ID INT OUTPUT,
    @ERROR_DESCRIPCION NVARCHAR(MAX) OUTPUT
)
AS
BEGIN
    BEGIN TRY
        INSERT INTO [dbo].[Usuarios]
        (
            [ID_PRODUCTOS],
            [ROL_USUARIO],
            [NOMBRE],
            [APELLIDO],
            [NUMERO],
            [DESCRIPCION],
            [REQUEST],
            [RESPONSE],
            [FECHA_REGISTRO]
        )
        VALUES
        (
            @ID_PRODUCTOS,
            @ROL_USUARIO,
            @NOMBRE,
            @APELLIDO,
            @NUMERO,
            @DESCRIPCION,
            @REQUEST,
            @RESPONSE,
            @FECHA_REGISTRO
        );

        SET @ID_RETURN = SCOPE_IDENTITY();
        SET @ERROR_ID = 0;
        SET @ERROR_DESCRIPCION = '';
    END TRY
    BEGIN CATCH
        SET @ID_RETURN = 0;
        SET @ERROR_ID = ERROR_NUMBER();
        SET @ERROR_DESCRIPCION = ERROR_MESSAGE();
    END CATCH;
END
GO--> insert para tabla usuario
CREATE PROCEDURE [dbo].[SP_INSERTAR_PRODUCTO_SODA]
(
    @NOMBRE NVARCHAR(MAX),
    @DESCRIPCION NVARCHAR(MAX),
    @PRECIO INT,
    @DISPONIBLE NVARCHAR(MAX),
    @FECHA_REGISTRO DATETIME,
    @ID_USUARIOS INT, 
    @ID_RETURN INT OUTPUT,
    @ERROR_ID INT OUTPUT,
    @ERROR_DESCRIPCION NVARCHAR(MAX) OUTPUT
)
AS
BEGIN
    BEGIN TRY
        INSERT INTO [dbo].[PRODUCTOS_SODA]
        (
            [NOMBRE],
            [DESCRIPCION],
            [PRECIO],
            [DISPONIBLE],
            [FECHA_REGISTRO],
            [ID_USUARIOS]
        )
        VALUES
        (
            @NOMBRE,
            @DESCRIPCION,
            @PRECIO,
            @DISPONIBLE,
            @FECHA_REGISTRO,
            @ID_USUARIO
        );

        SET @ID_RETURN = SCOPE_IDENTITY();
        SET @ERROR_ID = 0;
        SET @ERROR_DESCRIPCION = '';
    END TRY
    BEGIN CATCH
        SET @ID_RETURN = 0;
        SET @ERROR_ID = ERROR_NUMBER();
        SET @ERROR_DESCRIPCION = ERROR_MESSAGE();
    END CATCH;
END
GO--> insert para tabla prodcutos soda
CREATE PROCEDURE [dbo].[SP_INSERTAR_PEDIDO_SODA]
(
    @ID_USUARIOS INT,
    @FECHA_REGISTRO DATETIME,
    @ESTADO NVARCHAR(MAX),
    @ADICIONAL NVARCHAR(MAX),
    @PRECIOTOTAL INT,
    @ID_RETURN INT OUTPUT,
    @ERROR_ID INT OUTPUT,
    @ERROR_DESCRIPCION NVARCHAR(MAX) OUTPUT
)
AS
BEGIN
    BEGIN TRY
        INSERT INTO [dbo].[PEDIDOS_SODA]
        (
            [ID_USUARIOS],
            [FECHA_REGISTRO],
            [ESTADO],
            [ADICIONAL],
            [PRECIOTOTAL]
        )
        VALUES
        (
            @ID_USUARIOS,
            @FECHA_REGISTRO,
            @ESTADO,
            @ADICIONAL,
            @PRECIOTOTAL
        );

        SET @ID_RETURN = SCOPE_IDENTITY();
        SET @ERROR_ID = 0;
        SET @ERROR_DESCRIPCION = '';
    END TRY
    BEGIN CATCH
        SET @ID_RETURN = 0;
        SET @ERROR_ID = ERROR_NUMBER();
        SET @ERROR_DESCRIPCION = ERROR_MESSAGE();
    END CATCH;
END
GO--> insert para tabla pedidos soda
CREATE PROCEDURE [dbo].[SP_INSERTAR_ERROR_DB_SODA]
(
    @SEVERIDAD INT,
    @STORE_PROCEDURE NVARCHAR(50),
    @NUMERO INT,
    @DESCRIPCION NVARCHAR(MAX),
    @LINEA INT,
    @FECHA_HORA DATETIME,
    @ID_RETURN INT OUTPUT,
    @ERROR_ID INT OUTPUT,
    @ERROR_DESCRIPCION NVARCHAR(MAX) OUTPUT
)
AS
BEGIN
    BEGIN TRY
        INSERT INTO [dbo].[ERROR_DB_SODA]
        (
            [SEVERIDAD],
            [STORE_PROCEDURE],
            [NUMERO],
            [DESCRIPCION],
            [LINEA],
            [FECHA_HORA]
        )
        VALUES
        (
            @SEVERIDAD,
            @STORE_PROCEDURE,
            @NUMERO,
            @DESCRIPCION,
            @LINEA,
            @FECHA_HORA
        );

        SET @ID_RETURN = SCOPE_IDENTITY();
        SET @ERROR_ID = 0;
        SET @ERROR_DESCRIPCION = '';
    END TRY
    BEGIN CATCH
        SET @ID_RETURN = 0;
        SET @ERROR_ID = ERROR_NUMBER();
        SET @ERROR_DESCRIPCION = ERROR_MESSAGE();
    END CATCH;
END
GO--> insert para tabla errores soda
CREATE PROCEDURE [dbo].[SP_INSERTAR_RESPUESTA]
(
    @MENSAJE NVARCHAR(MAX),
    @FECHA_REGISTRO DATETIME,
    @ID_RETURN INT OUTPUT,
    @ERROR_ID INT OUTPUT,
    @ERROR_DESCRIPCION NVARCHAR(MAX) OUTPUT
)
AS
BEGIN
    BEGIN TRY
        INSERT INTO [dbo].[RESPUESTA]
        (
            [MENSAJE],
            [FECHA_REGISTRO]
        )
        VALUES
        (
            @MENSAJE,
            @FECHA_REGISTRO
        );

        SET @ID_RETURN = SCOPE_IDENTITY();
        SET @ERROR_ID = 0;
        SET @ERROR_DESCRIPCION = '';
    END TRY
    BEGIN CATCH
        SET @ID_RETURN = 0;
        SET @ERROR_ID = ERROR_NUMBER();
        SET @ERROR_DESCRIPCION = ERROR_MESSAGE();
    END CATCH;
END
GO--> insert para tabla  respuesta
CREATE PROCEDURE [dbo].[SP_INSERTAR_PUBLICAR_RESPUESTA]
(
    @ID_PUBLICACION INT,
    @ID_RESPUESTA INT,
    @FECHA_REGISTRO DATETIME,
    @ID_RETURN INT OUTPUT,
    @ERROR_ID INT OUTPUT,
    @ERROR_DESCRIPCION NVARCHAR(MAX) OUTPUT
)
AS
BEGIN
    BEGIN TRY
        INSERT INTO [dbo].[PUBLICAR_RESPUESTA]
        (
            [ID_PUBLICACION],
            [ID_RESPUESTA],
            [FECHA_REGISTRO]
        )
        VALUES
        (
            @ID_PUBLICACION,
            @ID_RESPUESTA,
            @FECHA_REGISTRO
        );

        SET @ID_RETURN = SCOPE_IDENTITY();
        SET @ERROR_ID = 0;
        SET @ERROR_DESCRIPCION = '';
    END TRY
    BEGIN CATCH
        SET @ID_RETURN = 0;
        SET @ERROR_ID = ERROR_NUMBER();
        SET @ERROR_DESCRIPCION = ERROR_MESSAGE();
    END CATCH;
END
GO--> insert para tabla publicar respuesta 


CREATE PROCEDURE [dbo].[SP_ACTUALIZAR_USUARIO]
(
    @ID_USUARIO INT,
    @ID_PRODUCTOS INT,
    @ROL_USUARIO NVARCHAR(100),
    @NOMBRE NVARCHAR(100),
    @APELLIDO NVARCHAR(100),
    @NUMERO NVARCHAR(100),
    @DESCRIPCION NVARCHAR(MAX),
    @REQUEST NVARCHAR(MAX),
    @RESPONSE NVARCHAR(MAX),
    @FECHA_REGISTRO DATETIME,
    @ERROR_ID INT OUTPUT,
    @ERROR_DESCRIPCION NVARCHAR(MAX) OUTPUT
)
AS
BEGIN
    BEGIN TRY
        UPDATE [dbo].[Usuarios]
        SET
            [ID_PRODUCTOS] = @ID_PRODUCTOS,
            [ROL_USUARIO] = @ROL_USUARIO,
            [NOMBRE] = @NOMBRE,
            [APELLIDO] = @APELLIDO,
            [NUMERO] = @NUMERO,
            [DESCRIPCION] = @DESCRIPCION,
            [REQUEST] = @REQUEST,
            [RESPONSE] = @RESPONSE,
            [FECHA_REGISTRO] = @FECHA_REGISTRO
        WHERE
            [ID_USUARIOS] = @ID_USUARIO;

        SET @ERROR_ID = 0;
        SET @ERROR_DESCRIPCION = '';
    END TRY
    BEGIN CATCH
        SET @ERROR_ID = ERROR_NUMBER();
        SET @ERROR_DESCRIPCION = ERROR_MESSAGE();
    END CATCH;
END 
GO --> update para tabla usuario
CREATE PROCEDURE [dbo].[SP_ACTUALIZAR_PRODUCTO_SODA]
(
    @ID_PRODUCTOS INT,
    @NOMBRE NVARCHAR(MAX),
    @DESCRIPCION NVARCHAR(MAX),
    @PRECIO INT,
    @DISPONIBLE NVARCHAR(MAX),
    @FECHA_REGISTRO DATETIME,
    @ERROR_ID INT OUTPUT,
    @ERROR_DESCRIPCION NVARCHAR(MAX) OUTPUT
)
AS
BEGIN
    BEGIN TRY
        UPDATE [dbo].[PRODUCTOS_SODA]
        SET
            [NOMBRE] = @NOMBRE,
            [DESCRIPCION] = @DESCRIPCION,
            [PRECIO] = @PRECIO,
            [DISPONIBLE] = @DISPONIBLE,
            [FECHA_REGISTRO] = @FECHA_REGISTRO
        WHERE
            [ID_PRODUCTOS] = @ID_PRODUCTOS;

        SET @ERROR_ID = 0;
        SET @ERROR_DESCRIPCION = '';
    END TRY
    BEGIN CATCH
        SET @ERROR_ID = ERROR_NUMBER();
        SET @ERROR_DESCRIPCION = ERROR_MESSAGE();
    END CATCH;
END
GO--> update para tabla prodcutos soda
x(
    @ID_PEDIDOS INT,
    @ID_USUARIOS INT,
    @FECHA_REGISTRO DATETIME,
    @ESTADO NVARCHAR(MAX),
    @ADICIONAL NVARCHAR(MAX),
    @PRECIOTOTAL INT,
    @ERROR_ID INT OUTPUT,
    @ERROR_DESCRIPCION NVARCHAR(MAX) OUTPUT
)
AS
BEGIN
    BEGIN TRY
        UPDATE [dbo].[PEDIDO_SODA]
        SET
            [ID_USUARIOS] = @ID_USUARIOS,
            [FECHA_REGISTRO] = @FECHA_REGISTRO,
            [ESTADO] = @ESTADO,
            [ADICIONAL] = @ADICIONAL,
            [PRECIOTOTAL] = @PRECIOTOTAL
        WHERE
            [ID_PEDIDOS] = @ID_PEDIDOS;

        SET @ERROR_ID = 0;
        SET @ERROR_DESCRIPCION = '';
    END TRY
    BEGIN CATCH
        SET @ERROR_ID = ERROR_NUMBER();
        SET @ERROR_DESCRIPCION = ERROR_MESSAGE();
    END CATCH;
END
GO--> update para tabla pedidos soda
CREATE PROCEDURE [dbo].[SP_ACTUALIZAR_ERROR_DB_SODA]
(
    @ID INT,
    @SEVERIDAD INT,
    @STORE_PROCEDURE NVARCHAR(50),
    @NUMERO INT,
    @DESCRIPCION NVARCHAR(MAX),
    @LINEA INT,
    @FECHA_HORA DATETIME,
    @ERROR_ID INT OUTPUT,
    @ERROR_DESCRIPCION NVARCHAR(MAX) OUTPUT
)
AS
BEGIN
    BEGIN TRY
        UPDATE [dbo].[ERROR_DB_SODA]
        SET
            [SEVERIDAD] = @SEVERIDAD,
            [STORE_PROCEDURE] = @STORE_PROCEDURE,
            [NUMERO] = @NUMERO,
            [DESCRIPCION] = @DESCRIPCION,
            [LINEA] = @LINEA,
            [FECHA_HORA] = @FECHA_HORA
        WHERE
            [ID] = @ID;

        SET @ERROR_ID = 0;
        SET @ERROR_DESCRIPCION = '';
    END TRY
    BEGIN CATCH
        SET @ERROR_ID = ERROR_NUMBER();
        SET @ERROR_DESCRIPCION = ERROR_MESSAGE();
    END CATCH;
END
GO--> update para tabla errores soda
CREATE PROCEDURE [dbo].[SP_ACTUALIZAR_RESPUESTA]
(
    @ID_USUARIO INT,
    @MENSAJE NVARCHAR(MAX),
    @FECHA_REGISTRO DATETIME,
    @ERROR_ID INT OUTPUT,
    @ERROR_DESCRIPCION NVARCHAR(MAX) OUTPUT
)
AS
BEGIN
    BEGIN TRY
        UPDATE [dbo].[RESPUESTA]
        SET
            [MENSAJE] = @MENSAJE,
            [FECHA_REGISTRO] = @FECHA_REGISTRO
        WHERE
            [ID_USUARIO] = @ID_USUARIO;

        SET @ERROR_ID = 0;
        SET @ERROR_DESCRIPCION = '';
    END TRY
    BEGIN CATCH
        SET @ERROR_ID = ERROR_NUMBER();
        SET @ERROR_DESCRIPCION = ERROR_MESSAGE();
    END CATCH;
END
GO--> update para tabla  respuesta 
CREATE PROCEDURE [dbo].[SP_ACTUALIZAR_PUBLICAR_RESPUESTA]
(
    @ID_PUBLICACION_RESPUESTA INT,
    @ID_PUBLICACION INT,
    @ID_RESPUESTA INT,
    @FECHA_REGISTRO DATETIME,
    @ERROR_ID INT OUTPUT,
    @ERROR_DESCRIPCION NVARCHAR(MAX) OUTPUT
)
AS
BEGIN
    BEGIN TRY
        UPDATE [dbo].[PUBLICAR_RESPUESTA]
        SET
            [ID_PUBLICACION] = @ID_PUBLICACION,
            [ID_RESPUESTA] = @ID_RESPUESTA,
            [FECHA_REGISTRO] = @FECHA_REGISTRO
        WHERE
            [ID_PUBLICACION_RESPUESTA] = @ID_PUBLICACION_RESPUESTA;

        SET @ERROR_ID = 0;
        SET @ERROR_DESCRIPCION = '';
    END TRY
    BEGIN CATCH
        SET @ERROR_ID = ERROR_NUMBER();
        SET @ERROR_DESCRIPCION = ERROR_MESSAGE();
    END CATCH;
END
GO--> update para tabla publicar respuesta 





